cpu한번에 처리할수 있는 용량 : 32bit 기준

8bit -> 2^8 (숫자 표현 갯수)


정수 : int  4byte - 32bit   / 1 byte = 8 bits 
  
소수 : float(부동 소숫점- 둥둥 떠다닌다) 4byte - 32bit

정규화 :normalization - 소숫점을 옮긴다,, <- x2 / -> /2

지수부 = -126~126까지 표현 : 00000001 = -126 / 11111110 = 126
가수부

1TB = 1000/1024 GB = (1000/1024)^2 MB = (1000/1024)^3 KB = (1000/1024)^4 Byte 
여기서 나오는 손실 -> 1TB= 930GB


뭔가 열려있다면 닫아야한다
같은폴더면 경로 필요 x

열고 쓰고 닫고?
열고 읽고 닫고?
아래는 왜 되지

In [1]:
f4=open("test2.txt","r")
print(f4.read())

f4.seek(0)
print(f4.tell())

context=f4.readlines()
print(context)

f4.close()

hello
안녕
반가워
난, 코딩온이야
0
['hello\n', '안녕\n', '반가워\n', '난, 코딩온이야']


In [ ]:
with open("example.txt","a") as file: # close 없어도 된다. # 뒤에다 적어줌
  file.write("\nhi\n")
  
with open("example.txt","r") as file: 
  print(file.read())

In [11]:
with open("N_example.txt","x") as file: # x 파일이 없어야 만들어짐 / 이미 존재하는 경우 error
  file.write("\nhi\n")
  

FileExistsError: [Errno 17] File exists: 'N_example.txt'

In [ ]:
member_info=str()
for _ in range(3):
  member_info=input("회원3명의 이름 비밀번호 입력")+'\n'
  with open("member.txt",'a') as file:
    file.write(member_info)


with open("member.txt", "r") as fi: 
    line = fi.readline()
    while line:
        print(line.strip())
        line = fi.readline()
        
name=input("이름을 입력하세요")
pw=input("비밀번호를 입력하세요")

member_check=name+' '+pw


with open("member.txt", "r") as fi: 
  
  line = fi.readline()
  while line:
    if member_check==line.strip():
      print("로그인 성공")
      break
    print("로그인 실패")
    line = fi.readline()
    
    
phone_number=input("전화번호를 입력하세요")
member_tel_info=member_check+' '+phone_number

with open("member_tel.txt",'+r') as file:
  
  adjust=file.tell() #파일을 읽기전 시작위치 받음
  old_info=file.readline() #한줄 읽음
  while old_info: 
    if member_check in old_info.strip(): #만약 읽어온 줄과 멤버 정보 일치 시
      file.seek(adjust) #시작하는 위치에 
      file.write(member_tel_info+'\n') #덮어쓰기..?
      break
    adjust=file.tell() #시작위치반환
    old_info=file.readline() #한줄 읽음
    
  if len(old_info)==0:
    file.write(member_tel_info+'\n') #맨 뒤에 추가

In [36]:
member_info=str()
for _ in range(3):
  member_info=input("회원3명의 이름 비밀번호 입력")+'\n'
  with open("member.txt",'a') as file:
    file.write(member_info)


with open("member.txt", "r") as fi: 
    line = fi.readline()
    while line:
        print(line.strip())
        line = fi.readline()

['john 1234\n', 'kevin 2345\n', 'go 4567\n']


In [93]:
name=input("이름을 입력하세요")
pw=input("비밀번호를 입력하세요")

member_check=name+' '+pw


with open("member.txt", "r") as fi: 
  
  line = fi.readline()
  while line:
    if member_check==line.strip():
      print("로그인 성공")
      break
    print("로그인 실패")
    line = fi.readline()
    

로그인 실패
로그인 성공


In [97]:
phone_number=input("전화번호를 입력하세요")
member_tel_info=member_check+' '+phone_number

with open("member_tel.txt",'+r') as file:
  
  adjust=file.tell() #파일을 읽기전 시작위치 받음 
  old_info=file.readline() #한줄 읽음
  while old_info: 
    if member_check in old_info.strip(): #만약 읽어온 줄과 멤버 정보 일치 시
      file.seek(adjust) #시작하는 위치에 
      file.write(member_tel_info+'\n') #덮어쓰기..?
      break
    adjust=file.tell() #시작위치 
    old_info=file.readline() #한줄 읽음
    
  if len(old_info)==0:
    file.write(member_tel_info+'\n') #맨 뒤에 추가

enumerate -> 순서쌍

name = input("input name")
pw = input("input pw")
isLogin = False
with open("member.txt","r") as file:
  lines = file.readlines()
  file.seek(0)
  for line in lines:
    text = line.split()# [ name, pw ]
    if len(text) >= 2 and text[0] == name and text[1] == pw:
      isLogin= True
      break
if isLogin:
  print("log in")
else :
  print("log in failed")
if isLogin:
  telNum = input("input tel num")
  with open("member_tel.txt","r+") as file:
    lines = file.readlines()
    file.seek(0)
    for i, line in enumerate(lines): # mylist = ['A', 'B', 'C'] -> (0, 'A'), (1, 'B'), (2,'C')
      text = line.split()
      if text and text[0] == name:
        lines[i] = f"{name} {telNum}\n"
        break
    else:
      lines.append(f"{name} {telNum}\n")
    file.writelines(lines)

In [102]:
while(1):
  try:
    int(input("숫자입력:"))
    print("정수 입력 성공")
    break
  except ValueError:
    print("정수가 아님! 정수를 입력해주세요!")


정수가 아님! 정수를 입력해주세요!
정수가 아님! 정수를 입력해주세요!


import numpy as np
matmul(a,b) # 행렬의 행렬곱 연산 
np.zeros()
np.ones()
np.full((2,3),5)
np.eye(3)
.reshape()
.arange() # 배열생성
random.rand(m,n)


In [129]:
import numpy as np 

zero_array=np.zeros(10) #10개의 0이 잇는 array
print(zero_array)

zero_array[4]=1 #그 array의 5번째 값 변경
print(zero_array)

ten_thirty=np.arange(10,31) #10~30 
print(ten_thirty)

random_array=np.random.randint(0,100,(2,2))
print(random_array)

random_array_2=np.random.rand(2,4)
print(random_array_2)




[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[[33 72]
 [32 71]]
[[0.98640131 0.48413686 0.2869049  0.94674176]
 [0.00200207 0.23844603 0.00154856 0.72878962]]


In [149]:

np6=np.arange(35,75)
np6=np6.reshape(10,4)
#print(np6)

np7=np6[::-1]
#print(np7)

np8=np6[1:-1,2:] # [행/열]
#print(np8)

np9=np6[:,3]
#np9=np9.flatten()
print(np9)

np9_2=np6[:,3:]
#np9_2=np9_2.reshape(10,1)
print(np9_2)

np10=np9_2[-1::-1]
print(np10)

[38 42 46 50 54 58 62 66 70 74]
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]
[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]


In [153]:
np11=np.random.randint(1,51,size=(5,6))
print(np11)
np11[np11%2==0]

[[44 49 35 28 10  1]
 [13 40  9 40 42 33]
 [35 41 18  9 21 18]
 [30 42 45  6 43 34]
 [20 17  8 11 22 15]]


array([44, 28, 10, 40, 40, 42, 18, 18, 30, 42,  6, 34, 20,  8, 22])

In [160]:
import numpy as np
data=[1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]

data_sort=np.unique(data)
print(data_sort)
max_data=np.max(data_sort)
min_data=np.min(data_sort)
avg_data=np.mean(data_sort)
sum_data=np.sum(data_sort)
medium_data=np.median(data)

print(max_data,min_data,avg_data,sum_data,medium_data)

[  1   2   3   4   5   7   8   9  10  11  24 100]
100 1 15.333333333333334 184 5.0
